"""
Generate a SIZE x SIZE maze-like grid of 0s and 1s.

1 = open path, 0 = wall. All 1s form a single 4-connected region, and the
paths are spread evenly over the whole grid like a maze.

Method: the grid is treated as a lattice of "rooms" at even (row, col)
positions, with the odd positions between them acting as potential doors.
A randomized depth-first search carves a spanning tree through the rooms
(a "perfect maze": exactly one route between any two open cells). Because
the search visits every room, the corridors cover the entire grid.

Optionally, LOOP_CHANCE knocks out extra walls so the maze has loops and
multiple routes instead of a single solution.
"""
# generated by claude sonnet 5.5

import os
import random
from collections import deque
import matplotlib.pyplot as plt

SIZE = 99
LOOP_CHANCE = 0.0   # 0.0 = perfect maze (no loops); try 0.02-0.10 for loops
SEED = None         # set to an int for reproducible output

DIRS = ((1, 0), (-1, 0), (0, 1), (0, -1))


def generate_maze(size=SIZE, loop_chance=LOOP_CHANCE, seed=SEED):
    rng = random.Random(seed)
    grid = [[0] * size for _ in range(size)]

    # Rooms live at even coordinates: 0, 2, ..., (last even index <= size-1)
    n = (size + 1) // 2  # rooms per side

    # Randomized DFS (iterative, to avoid recursion limits)
    sr, sc = rng.randrange(n) * 2, rng.randrange(n) * 2
    grid[sr][sc] = 1
    stack = [(sr, sc)]

    while stack:
        r, c = stack[-1]
        options = []
        for dr, dc in DIRS:
            nr, nc = r + 2 * dr, c + 2 * dc
            if 0 <= nr < size and 0 <= nc < size and not grid[nr][nc]:
                options.append((dr, dc, nr, nc))
        if not options:
            stack.pop()
            continue
        dr, dc, nr, nc = rng.choice(options)
        grid[r + dr][c + dc] = 1   # knock out the wall between the rooms
        grid[nr][nc] = 1
        stack.append((nr, nc))

    # Optional: open extra walls between rooms to create loops
    if loop_chance > 0:
        for r in range(size):
            for c in range(size):
                if grid[r][c]:
                    continue
                if r % 2 == 1 and c % 2 == 0 and r + 1 < size:
                    if rng.random() < loop_chance:
                        grid[r][c] = 1   # vertical door between two rooms
                elif r % 2 == 0 and c % 2 == 1 and c + 1 < size:
                    if rng.random() < loop_chance:
                        grid[r][c] = 1   # horizontal door between two rooms

    return grid


def is_connected(grid):
    """BFS check that all 1-cells form a single 4-connected component."""
    size = len(grid)
    ones = sum(map(sum, grid))
    if ones == 0:
        return True

    start = next((r, c) for r in range(size) for c in range(size) if grid[r][c])
    seen = {start}
    q = deque([start])
    while q:
        r, c = q.popleft()
        for dr, dc in DIRS:
            nr, nc = r + dr, c + dc
            if 0 <= nr < size and 0 <= nc < size and grid[nr][nc] and (nr, nc) not in seen:
                seen.add((nr, nc))
                q.append((nr, nc))
    return len(seen) == ones


def quadrant_density(grid):
    """Fraction of 1s in each quarter of the grid, to show even coverage."""
    h = len(grid) // 2
    quads = [(0, h, 0, h), (0, h, h, len(grid)), (h, len(grid), 0, h), (h, len(grid), h, len(grid))]
    out = []
    for r0, r1, c0, c1 in quads:
        total = (r1 - r0) * (c1 - c0)
        ones = sum(sum(row[c0:c1]) for row in grid[r0:r1])
        out.append(ones / total)
    return out


if __name__ == "__main__":
    grid = generate_maze()

    ones = sum(map(sum, grid))
    print(f"Grid: {len(grid)}x{len(grid[0])}, ones: {ones}, zeros: {SIZE * SIZE - ones}")
    print("All 1s connected:", is_connected(grid))
    print("Density per quadrant:", [round(d, 3) for d in quadrant_density(grid)])

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "grid.txt")
    try:
        with open(out_path, "w") as f:
            for row in grid:
                f.write("".join(map(str, row)) + "\n")
        print("Saved to:", out_path)
    except OSError as e:
        print("Could not save file:", e)


    plt.matshow(grid)
    plt.show()